name: Clippy Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:

      - name: deps
        run: sudo apt update && sudo apt install gcc-multilib g++-multilib

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all --tests
